# Generated by Django 2.0.13 on 2020-04-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sohwan',
            name='rank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sohwan',
            name='tier',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
